### Criar tarefa
POST http://localhost:3000/tarefas
Content-Type: application/json

{
  "titulo": "Estudar Node.js",
  "descricao": "Terminar o CRUD com MySQL"
}

### Listar tarefas
GET http://localhost:3000/tarefas

### Atualizar tarefa
PUT http://localhost:3000/tarefas/1
Content-Type: application/json

{
  "completada": true
}

### Deletar tarefa
DELETE http://localhost:3000/tarefas/0